### ISSUE TITLE
Feature request: please support Chromecast IP and port configuration

### ISSUE THREAD

**Issue by BradJJ2000** [paolotremadio/homebridge-automation-chromecast#21]
This is exactly what I need to turn on my HomeKit controlled receiver when I stream and turn it off with a delay once I stop streaming. I run Homebridge in docker on QNAP NAS which doesn’t have mDNS. 

I would love to be able to configure this for my chromecasts that have static ip addresses on my QNAP docker. 

If anyone has a solution or alternative then please reply.

**Comment by paolotremadio** [comment]
Hi, I do agree with you: having static IPs would make it simpler when running in complex network environment. 

The only issue is: the plug-in works on mDNS for two reason: to discover the chromecast and to monitor chromecast reboots. 

Having a static IP would fix the first issue but what happens when the chromecast goes offline? How do you know is back online? 

It would be a bit of a change trying to make it work without mDNS. 

Can you configure your container to work on the `host` network? That way it would detect the chromecast.
